# -*- coding: utf-8 -*-
"""DSCI352_HW2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zKtgRUjtLs4I-9INnKNgdZrTgwQBopNY
"""

# Credit: https://github.com/christianversloot/machine-learning-articles/blob/main/linking-maths-and-intuition-rosenblatts-perceptron-in-python.md?plain=1

import numpy as np

## Prepare a dataset

# Generate target classes {0, 1}
zeros = np.zeros(50)
ones = zeros + 1
targets = np.concatenate((zeros, ones))

# print(zeros)
# print(ones)
# print(targets)

# Generate data
# normal has attributes mu, sigma, output shape
small = np.random.normal(5, 0.25, (50,2))
large = np.random.normal(6.5, 0.25, (50,2))

# print(small)
# print(large)

# Prepare input data
X = np.concatenate((small,large))
T = targets

### Visualizing the dataset

from mlxtend.plotting import plot_decision_regions
import matplotlib.pyplot as plt
plt.scatter(small[:,0], small[:,1], color='blue')
plt.scatter(large[:,0], large[:,1], color='red')
plt.show()

# Rosenblatt Perceptron

import numpy as np

# Basic Rosenblatt Perceptron implementation
class RBPerceptron():

  # Constructor object, self is the instance of the object NeuralNetwork itself
  def __init__(self, number_of_epochs = 100, learning_rate = 0.1):
    self.number_of_epochs = number_of_epochs
    self.learning_rate = learning_rate

  # Train perceptron
  def train(self, X, T):
    # Initialize weights vector with zeroes
    num_features = X.shape[1]
    self.w = np.zeros(num_features + 1)
    # Perform the epochs
#    diff = []
#    err = []
    for i in range(self.number_of_epochs):
#      err.append(sum(diff))
#      print(err)
      # For every combination of (X_i, T_i), zip creates the tuples
      for sample, desired_outcome in zip(X, T):
        # Generate prediction and compare with desired outcome
        prediction    = self.predict(sample)
        difference    = (desired_outcome - prediction)
#        diff.append(difference)
        # Compute weight update via Perceptron Learning Rule
        self.w[1:]    += self.learning_rate * difference * sample
        self.w[0]     += self.learning_rate * difference * 1
    return self

  # Generate prediction
  def predict(self, sample):
    # dot product:
    outcome = np.dot(sample, self.w[1:]) + self.w[0]
    # Activation function:
    return np.where(outcome > 0, 1, 0)

# ks = [100,200,300,400,500,600,700, 800, 900, 1000]
ks = [100,200, 300, 500]
colors = ['blue','limegreen','gray','cyan','red','red','red']

for k in ks:
  # print(k)
  rbp = RBPerceptron(k, 0.1)
  trained_model = rbp.train(X, T)

  plot_decision_regions(X, T.astype(np.integer), clf=trained_model, legend=0)

plt.title('Perceptron')
plt.xlabel('X1')
plt.ylabel('X2')
plt.show()

"""#4a"""

import pandas as pd

iris_df = pd.read_csv('Iris.csv')

import numpy as np

# 1. Filter the iris_df to include only 'Iris-setosa' and 'Iris-versicolor' species.
iris_subset = iris_df[iris_df['Species'].isin(['Iris-setosa', 'Iris-versicolor'])]

# 2. Select 'SepalLengthCm' and 'PetalLengthCm' as features (X_iris).
X_iris = iris_subset[['SepalLengthCm', 'PetalLengthCm']].values

# 3. Convert 'Species' to numerical targets (T_iris).
T_iris = np.where(iris_subset['Species'] == 'Iris-setosa', 0, 1)

import matplotlib.pyplot as plt

# Create a scatter plot
plt.figure(figsize=(8, 6))
sns.scatterplot(
    data=iris_subset,
    x='SepalLengthCm',
    y='PetalLengthCm',
    hue='Species',
    palette={'Iris-setosa': 'blue', 'Iris-versicolor': 'red'},
    s=100
)

# Add labels and title
plt.xlabel('Sepal Length (Cm)')
plt.ylabel('Petal Length (Cm)')
plt.title('Sepal Length vs. Petal Length for Setosa and Versicolor')

# Display legend
plt.legend(title='Species')

# Show the plot
plt.grid(True)
plt.show()

from mlxtend.plotting import plot_decision_regions
import matplotlib.pyplot as plt

# Instantiate the RBPerceptron model
# A small number of epochs (e.g., 100) and learning rate (e.g., 0.1) should be sufficient for linearly separable data
rbp_iris = RBPerceptron(number_of_epochs=100, learning_rate=0.1)

# Train the perceptron model on the Iris subset
trained_iris_model = rbp_iris.train(X_iris, T_iris)

# Plot the decision regions
plt.figure(figsize=(8, 6))
plot_decision_regions(X_iris, T_iris, clf=trained_iris_model, legend=0)

plt.xlabel('Sepal Length (Cm)')
plt.ylabel('Petal Length (Cm)')
plt.title('Perceptron Decision Regions for Iris Setosa vs. Versicolor')
plt.show()

"""#4b"""

X_iris_new = iris_subset[['SepalWidthCm', 'PetalWidthCm']].values

import matplotlib.pyplot as plt
import seaborn as sns

# Create a scatter plot for the new features
plt.figure(figsize=(8, 6))
sns.scatterplot(
    data=iris_subset,
    x='SepalWidthCm',
    y='PetalWidthCm',
    hue='Species',
    palette={'Iris-setosa': 'blue', 'Iris-versicolor': 'red'},
    s=100
)

# Add labels and title
plt.xlabel('Sepal Width (Cm)')
plt.ylabel('Petal Width (Cm)')
plt.title('Sepal Width vs. Petal Width for Setosa and Versicolor')

# Display legend
plt.legend(title='Species')

# Show the plot
plt.grid(True)
plt.show()

from mlxtend.plotting import plot_decision_regions
import matplotlib.pyplot as plt

# Instantiate the RBPerceptron model
# A small number of epochs (e.g., 100) and learning rate (e.g., 0.1) should be sufficient for linearly separable data
rbp_iris_new = RBPerceptron(number_of_epochs=100, learning_rate=0.1)

# Train the perceptron model on the new Iris subset features
trained_iris_model_new = rbp_iris_new.train(X_iris_new, T_iris)

# Plot the decision regions
plt.figure(figsize=(8, 6))
plot_decision_regions(X_iris_new, T_iris, clf=trained_iris_model_new, legend=0)

plt.xlabel('Sepal Width (Cm)')
plt.ylabel('Petal Width (Cm)')
plt.title('Perceptron Decision Regions for Iris Setosa vs. Versicolor (Sepal Width, Petal Width)')
plt.show()